name: Blog Update
on:
  repository_dispatch:
    types: blog-update

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule init
        git submodule update
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 14
    - run: npm install
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: website
        path: public/
  publish:
    name: Publish Website
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: website
          path: website
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./website
          cname: www.davidwesst.com
          commit_message: "Blog Update - ${{ github.event.client_payload.sha }}"


 
      
