name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 14
    - run: npm install
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: website
        path: public/
